'use client'

import { useEffect, useState } from "react";
import { useLastRandomNumber } from "../hooks/useContractRead";

interface ResultDisplayProps {
  refreshTrigger?: number;
}

export default function ResultDisplay({ refreshTrigger }: ResultDisplayProps) {
  const { result, loading, refetch } = useLastRandomNumber(refreshTrigger);
  const [lastValue, setLastValue] = useState<number | null>(null);
  const [isNewResult, setIsNewResult] = useState(false);

  // Track when result changes to show animation
  useEffect(() => {
    if (result && result.value !== lastValue) {
      setIsNewResult(true);
      setLastValue(result.value);
      // Remove highlight after 2 seconds
      const timer = setTimeout(() => setIsNewResult(false), 2000);
      return () => clearTimeout(timer);
    }
  }, [result, lastValue]);

  // Auto-poll every 5 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      refetch();
    }, 5000);
    return () => clearInterval(interval);
  }, [refetch]);

  return (
    <div className="cyber-card p-6">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-lg font-bold text-white uppercase tracking-wide">
          Last Generated Result
        </h2>
        <button
          onClick={refetch}
          disabled={loading}
          className="neon-border-button px-4 py-2 rounded text-sm"
        >
          {loading ? "REFRESHING..." : "REFRESH"}
        </button>
      </div>

      {loading ? (
        <div className="text-center py-8 text-gray-500">
          <div className="animate-pulse text-[#39FF14]">Loading result...</div>
        </div>
      ) : result ? (
        <div 
          className="text-center py-8 rounded-lg transition-all duration-500"
          style={{
            backgroundColor: isNewResult ? 'rgba(57, 255, 20, 0.1)' : 'transparent',
          }}
        >
          <div 
            className="text-5xl font-bold mb-2 transition-all duration-500 glow-text"
            style={{ color: '#39FF14' }}
          >
            {result.value}
            {isNewResult && (
              <span className="text-sm ml-2 bg-[#39FF14] text-black px-2 py-1 rounded">
                ✓ NEW!
              </span>
            )}
          </div>
          <div className="text-sm text-gray-400 mb-2 uppercase tracking-wide">
            Range: <span className="text-white">{result.min}</span> - <span className="text-white">{result.max}</span>
          </div>
          <div className="text-xs text-gray-500 font-mono">
            Generated by: <span className="text-[#39FF14]/70">{result.generator.slice(0, 10)}...{result.generator.slice(-8)}</span>
          </div>
        </div>
      ) : (
        <div className="text-center py-8">
          <p className="text-gray-400 mb-2">
            No random number generated yet.
          </p>
          <p className="text-sm text-gray-500">
            Connect your wallet and generate your first random number!
          </p>
        </div>
      )}
    </div>
  );
}
