'use client'

import { useEffect, useState } from "react";
import { useLastRandomNumber } from "../hooks/useContractRead";

interface ResultDisplayProps {
  refreshTrigger?: number;
}

export default function ResultDisplay({ refreshTrigger }: ResultDisplayProps) {
  const { result, loading, refetch } = useLastRandomNumber(refreshTrigger);
  const [lastValue, setLastValue] = useState<number | null>(null);
  const [isNewResult, setIsNewResult] = useState(false);

  // Track when result changes to show animation
  useEffect(() => {
    if (result && result.value !== lastValue) {
      setIsNewResult(true);
      setLastValue(result.value);
      // Remove highlight after 2 seconds
      const timer = setTimeout(() => setIsNewResult(false), 2000);
      return () => clearTimeout(timer);
    }
  }, [result, lastValue]);

  // Auto-poll every 5 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      refetch();
    }, 5000);
    return () => clearInterval(interval);
  }, [refetch]);

  return (
    <div style={{
      border: "1px solid #e0e0e0",
      borderRadius: "0.5rem",
      padding: "1.5rem",
      backgroundColor: "white",
      boxShadow: "0 2px 4px rgba(0,0,0,0.1)"
    }}>
      <div style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: "1rem"
      }}>
        <h2 style={{ margin: 0, fontSize: "1.25rem" }}>
          Last Generated Result
        </h2>
        <button
          onClick={refetch}
          disabled={loading}
          style={{
            padding: "0.5rem 1rem",
            border: "1px solid #646cff",
            borderRadius: "0.25rem",
            backgroundColor: "transparent",
            color: "#646cff",
            cursor: loading ? "not-allowed" : "pointer",
            fontSize: "0.875rem"
          }}
        >
          {loading ? "Refreshing..." : "Refresh"}
        </button>
      </div>

      {loading ? (
        <div style={{
          textAlign: "center",
          padding: "2rem",
          color: "#666"
        }}>
          Loading result...
        </div>
      ) : result ? (
        <div style={{
          textAlign: "center",
          padding: "2rem",
          backgroundColor: isNewResult ? "#f0f9ff" : "transparent",
          borderRadius: "0.5rem",
          transition: "background-color 0.5s ease"
        }}>
          <div style={{
            fontSize: "3rem",
            fontWeight: "bold",
            color: isNewResult ? "#22c55e" : "#646cff",
            marginBottom: "0.5rem",
            transition: "color 0.5s ease"
          }}>
            {result.value}
            {isNewResult && <span style={{ fontSize: "1rem", marginLeft: "0.5rem" }}>✓ New!</span>}
          </div>
          <div style={{
            fontSize: "0.875rem",
            color: "#666",
            marginBottom: "0.5rem"
          }}>
            Range: {result.min} - {result.max}
          </div>
          <div style={{
            fontSize: "0.75rem",
            color: "#999",
            fontFamily: "monospace",
            wordBreak: "break-all"
          }}>
            Generated by: {result.generator.slice(0, 10)}...{result.generator.slice(-8)}
          </div>
        </div>
      ) : (
        <div style={{
          textAlign: "center",
          padding: "2rem",
          color: "#666"
        }}>
          <p style={{ marginTop: 0 }}>
            No random number generated yet.
          </p>
          <p style={{ marginBottom: 0, fontSize: "0.875rem" }}>
            Connect your wallet and generate your first random number!
          </p>
        </div>
      )}
    </div>
  );
}
